# Generated by Django 5.0.4 on 2024-04-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100, verbose_name='Идентификатор')),
                ('place_name', models.CharField(max_length=35, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Место покупки',
                'verbose_name_plural': 'Места покупок',
            },
        ),
        migrations.AddField(
            model_name='check',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.place', verbose_name='Продукт'),
        ),
    ]
